url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "sdot.co.uk" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  projects:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "default"